expose:
  type: clusterIP
  tls:
    enabled: false
externalURL: http://harbor.local


persistence:
  enabled: true
  persistentVolumeClaim:
    registry: { size: 5Gi }
    database: { size: 2Gi }
    redis: { size: 1Gi }
    jobservice: { size: 1Gi }


harborAdminPassword: "admin"

