name: CI
on:
  push:
    branches: [main]  
  pull_request:

permissions:
  contents: read

env:
  CI_IMAGE: local-ci:${{ github.sha }}


jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      
      - name: Trivy (config & fs)
        uses: aquasecurity/trivy-action@0.26.0
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'